backend:
  name: git-gateway
  repo: git-ayas/acanbiz-baseplate
  branch: master # Branch to update (optional; defaults to master)
# These lines should *not* be indented
media_folder: "public/images/uploads" # Media files will be stored in the repo under /public/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
publish_mode: editorial_workflow
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Short description",
          name: "description",
          widget: "string",
          pattern:
            ["^.{5,250}$", "Your input must be between 5 to 250 characters"],
        }
      - { label: "Published", name: "pubDate", widget: "datetime" }
      - {
          label: "Last Updated",
          name: "updatedDate",
          widget: "datetime",
          required: false,
        }
      - { label: "Featured Image", name: "heroImage", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
